.TH "Couple" 3 "Mon Feb 16 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Couple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmot\fP"
.br
.ti -1c
.RI "int \fBfrequence\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Couple::frequence"
Le nombre de fois où on retrouve le mot dans le texte 
.SS "string Couple::mot"
Le mot dans le texte 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
