.TH "Couple" 3 "Mon Feb 16 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Couple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmot\fP"
.br
.ti -1c
.RI "int \fBfrequence\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
